workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      vars:
        FLUTTER_VERSION: stable
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - mr.q8y911@gmail.com